apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: team-streaming-dev

resources:
  - ../../base/namespace.yaml
  - ../../base/resourcequota.yaml

patches:
  - target:
      kind: Namespace
      name: PLACEHOLDER
    patch: |
      - op: replace
        path: /metadata/name
        value: team-streaming-dev
      - op: add
        path: /metadata/labels/primetime.io~1team
        value: streaming
      - op: add
        path: /metadata/labels/primetime.io~1environment
        value: dev
