apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: content-acc

resources:
  - ../../../base

patches:
  - target:
      kind: Namespace
      name: PLACEHOLDER
    patch: |
      - op: replace
        path: /metadata/name
        value: content-acc
      - op: add
        path: /metadata/labels/primetime.io~1team
        value: content
      - op: add
        path: /metadata/labels/primetime.io~1environment
        value: acc
  - target:
      kind: ResourceQuota
      name: default
    patch: |
      - op: replace
        path: /metadata/name
        value: content-acc-limits
